### ISSUE TITLE
Dashes in Project Name leave VS unable to load project file

### ISSUE THREAD

**Issue by Meloncon** [spark-dotnet/framework#25]
When I use a dash in the project name it doesn't add the correct name for the .csproj file to the .sln file. For example, the project name: "Spark-App". The project file is created as intended, "Spark-App.csproj", but the .sln file contains "Spark_App.csproj" which causes `spark open` to launch VS and then VS cannot find the csproj file and it fails to load the solution.

Reproduce by:

1. Running `spark new Spark-App`
2. Change into directory: `cd Spark-App`
3. Run `spark open`

**Comment by Meloncon** [comment]
Of course, it might be bad practice to use a dash in your project name, as you can't name objects in C# with a dash. My project loads just fine after I modify the solution file to use the dash instead of underscore in the csproj name, but my namespace is, understandably, "Spark_App" in the codebase. Just an edge case, really.

Thanks for this project though! I love seeing this kind of innovation in the .NET world! 👍

**Comment by westonwalker** [comment]
Thanks for reporting. I've never really seen anyone name a .NET project with that pattern.

Having said that, it should work. I'll put this on my backlog.
