### ISSUE TITLE
CreatedAt not set in SQLite

### ISSUE THREAD

**Issue by JAzevedoDev** [spark-dotnet/framework#26]
Hello, I've only tested it with SQlite but the CreatedAT field isn't putting the current date - it's empty. It should be automatic, shouldn't it? Just as ModifyAt should also change automatically on Updates.

**Comment by westonwalker** [comment]
How were you saving the model. Do you mind sharing your code?

**Comment by JAzevedoDev** [comment]
Sure,

void AddRec()
    {
        using (var db = factory.CreateDbContext())
        {
            var a = new Article() { Title = $"new:{Articles.Count()}", Content = "test", UserId = 1, Slug = "ok3" };
            db.Articles.Add(a);
            db.SaveChanges();
            Articles = db.Articles.Include(x => x.User).OrderByDescending(x => x.CreatedAt).ToList();
            StateHasChanged();
        }
    }

**Comment by westonwalker** [comment]
So Entity Framework does not automattically set the CreatedAt field for you.

But Spark does come with custom extension methods that will do it for you.

You can read about them here: https://spark-framework.net/docs/data-access/#saving-updating-and-deleting-data

Here is a quick demo. Use the .Save() extension method:

var a = new Article() { Title = $"new:{Articles.Count()}", Content = "test", UserId = 1, Slug = "ok3" };
db.Articles.Save(a);

The Save() extension method is the equivalent of this:
var a = new Article() { Title = $"new:{Articles.Count()}", Content = "test", UserId = 1, Slug = "ok3" };
a..CreatedAt = DateTime.UtcNow;
db.Articles.Add(a);
db.SaveChanges();


The Save() extension method also works for updates. It will detect it's an existing record and set the UpdatedAt field instead.

**Comment by JAzevedoDev** [comment]
ya. nice. ty
