### ISSUE TITLE
Local IIS or Web SharkHost not working

### ISSUE THREAD

**Issue by JAzevedoDev** [spark-dotnet/framework#27]
Hello.
A fresh spark install, even without db migration dosent work, i get error HTTP Error 500.30 on local IIS or Shared Webhost.
I used the default .ENV file without change anything.

Everything works fine if i run the app on visualstudio

EventViewer:
Application: w3wp.exe
CoreCLR Version: 7.0.923.32018
.NET Version: 7.0.9
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception: Invalid database driver. Check your .env file and make sure the DB_CONNECTION variable is set to mysql, sqlite, postgres, or sqlserver.
   at Spark.Library.Database.DatabaseServiceRegistration.AddDatabase[T](IServiceCollection services, IConfiguration config)
   at SimpleSpark.Application.Startup.AppServiceRegistration.AddAppServices(IServiceCollection services, IConfiguration config) in C:\Lixo\SimpleSpark\Application\Startup\AppServiceRegistration.cs:line 23
   at Program.<Main>$(String[] args) in C:\Lixo\SimpleSpark\Program.cs:line 12

**Comment by JAzevedoDev** [comment]
This is strange because I created the project yesterday and the env file is in the root (.env) 
![image](https://github.com/spark-dotnet/framework/assets/790579/822bef11-86f5-4d97-86cd-2099827bde5a)

**Comment by JAzevedoDev** [comment]
@westonwalker Sorry for the trouble. when i published from my VSStudio to IIS he simple dosent copy the .ENV
I copied mannually and it's working!! Thank you.

**Comment by westonwalker** [comment]
Awesome, glad it's working. 

Sorry for the confusion, I don't think the .env bug I mentioned is actually a thing, just a symptom of some botched merges I had going on.
