### ISSUE TITLE
OAuth / SSO integration 

### ISSUE THREAD

**Issue by CarbonNeuron** [spark-dotnet/framework#32]
Hey Spark Team,

Just a note to say how much I'm enjoying working with Spark. You folks have seriously knocked it out of the park!

So, here's a thought. What if Spark had OAuth and SSO support? Over at Plainfield School District 202, we're hooked on Microsoft's authentication system. If we could get that sort of integration with Spark, it would be a game changer for us.

And I don't think it's just us. I can see loads of devs getting excited about spinning up secure, internal apps with OAuth and SSO support. Feels like it could be a real boost to what Spark already offers.

I get that this is a big ask. I'm just putting it out there, and I'm more than willing to talk about it or explore other ways we might get the same benefits. 

Once again, kudos on an amazing job with Spark. This is just a way we might be able to kick it up a notch.

Thanks for considering my suggestion! I've added it here as a GitHub issue for better tracking.

**Comment by westonwalker** [comment]
Sorry for the late response but I've been thinking this question over for a while and wanted to give a proper response. 

I get a lot of questions about supporting different types of auth, email, etc...

My plans moving forward is to create interface contracts for all Spark services. Spark will provide an implementation for the interface out of the box. For auth, this would be the standard cookie auth. Then devs using Spark can provide a different implementation for this interface if they'd like (in your case, OAUTH).

On top of this, I'll be open to pull requests to include popular implementations created by the community. So if OATH is popular, I would include it's implementation in Spark. A fresh Spark project would still use the standard Cookie auth but it could easily be changed to the OAUTH implementation when registering services.
