### ISSUE TITLE
Cannot resolve view 'Update' in PasswordController

### ISSUE THREAD

**Issue by mdabrarhassan** [spark-dotnet/framework#35]
I created the app using
```
spark new MyApp -t mvc -c bootstrap
```
It cannot resolve the views for the `PasswordController` and I do not see a corresponding `Views/Password` folder.

**Comment by westonwalker** [comment]
This was my mistake, The `PasswordController` should not be in the project. The `ProfileController` handles updating passwords. The view for updating passwords is the `Views/Profile/Edit.cshtml`. It references the `_ProfilePasswordEditor.cshtml` partial which has the password update form.

I will remove the `PasswordController.cs` file in the next Spark release.

**Comment by westonwalker** [comment]
This was fixed in the new 0.8.1 release. You will need to update your Spark templates. You can do that by running the "spark update" command in the terminal.
