### ISSUE TITLE
External Auth Providers? MS/AzureAD

### ISSUE THREAD

**Issue by bakes82** [spark-dotnet/framework#41]
Any plans to add the built-in MS Identity auth provider support, not sure who uses local auth anymore, especially with lots of companies requiring MFA etc that can be all configured on the auth provider as well as not need to manage removing access on termination since it's tied to the external provider.

**Comment by Simcon** [comment]
I haven't tested but it seems you don't need Identity for external auth:

[Use social sign-in provider authentication without ASP.NET Core Identity](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/social-without-identity?view=aspnetcore-7.0)

**Comment by bakes82** [comment]
> I haven't tested but it seems you don't need Identity for external auth:
> 
> [Use social sign-in provider authentication without ASP.NET Core Identity](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/social-without-identity?view=aspnetcore-7.0)

Sure if you just want to auth them and not use roles/permissions.  There is also more too it since blazor needs to do a full page post back for the external providers.
