### ISSUE TITLE
"spark make page <name>" file structure inconsistent with template

### ISSUE THREAD

**Issue by PelleRavn** [spark-dotnet/framework#45]
Hi,

Minor thing I just noticed: When creating a new page with `spark make page Profile/Settings`, it would create two new files `Profile/Settings.razor` and `Profile/Settings.cs`.
But that is a different naming than the ones that was created with the templates. Those files would be named something like `Profile/Settings.razor` and `Profile/Settings.razor.cs`, so it also adds the .cs file "under" (as a "fold out" file) the .razor file.

I think this should be easy to fix, and would make file creations more streamlined.

/Pelle

**Comment by westonwalker** [comment]
Thanks. Closing this since the make page command is going away in Spark 1.0
