### ISSUE TITLE
spark new [appname] --css bootstrap Not Working

### ISSUE THREAD

**Issue by PrashantUnity** [spark-dotnet/framework#52]
Hi there I am trying to use 
```spark new [appname] --css bootstrap```
Command it is not working.

Is it removed from the the spark CLI. Video is for reference for that case.

https://github.com/spark-dotnet/framework/assets/48068632/24aec1a0-a7a4-46c9-a75e-2aaf30f551b8

Also in source code i found out that there is no any configuration for --css [Link](https://github.com/spark-dotnet/framework/blob/master/Spark.Console/Program.cs)
<details>
<img src="https://github.com/spark-dotnet/framework/assets/48068632/1fa9370b-777f-420d-937d-fc6ebb417e5f"/>
</details> 
Could you please help me.

**Comment by dlplenin** [comment]
Hi, @PrashantUnity take a look at this [link](https://github.com/spark-dotnet/framework/commits/master/)
![image](https://github.com/spark-dotnet/framework/assets/2582026/9b601302-e780-4c87-937b-00abe3aa2443)

It was removed (--css), rigth? ... I was looking for the same coz I'm not familiar with tailwind**css** & when I want to see how to use a select-menu component tailwind**ui**.com asks me to pay...

**Comment by PrashantUnity** [comment]
@dlplenin sad that it is removed.

I give up when i found out that it is demanding for money 💰💰 🥲🥲.

In my perspective Bootstrap is clean short and also easier in manipulation using c#.
Plus point it is supported by  MudBlazor Library.

**Comment by steves-bits** [comment]
I know this is off-topic but in case people read this and get put off of Spark due to this. I would suggest Daisy UI is a nice free Tailwind component library. https://daisyui.com/

**Comment by PrashantUnity** [comment]
@steves-bits thankyou this is a huge help

**Comment by steves-bits** [comment]
@PrashantUnity glad to help. you may find this youtube frm .net conf interesting as a primer to Blazor with Tailwind CSS 
https://www.youtube.com/watch?v=QIdedo8iI4Y

**Comment by westonwalker** [comment]
@PrashantUnity Spark 1.0 was just released. It comes with Tailwind and DaisyUI installed for you. DaisyUI gives you css classes similar to Bootstrap.
