### ISSUE TITLE
API Template Request

### ISSUE THREAD

**Issue by jiaweing** [spark-dotnet/framework#65]
May I request for an API template? I mainly use .NET to build APIs only and use other frameworks for the frontend.

This was a thing before 1.0 but now we only have Blazor and Razor pages.

Thanks!

**Comment by cbmdk** [comment]
would be really awesome to have... included with usage on a sample page

**Comment by westonwalker** [comment]
I'm still on the fence about this. In the past I created multiple templates and it became very hard to keep all of the templates up to date and I removed them to lessen the load on myself.

**Comment by gaetandezeiraud** [comment]
Without a template, maybe a guide in the documentation about how to convert a Razor project to an API? Or similar.

**Comment by gaetandezeiraud** [comment]
So no more coming about this?
