### ISSUE TITLE
No title

### ISSUE THREAD

**Issue by Duelbat** [spark-dotnet/framework#66]

**Comment by punkouter24** [comment]
Im not sure why not just do it the old fashion way in the appsettings ?

**Comment by Duelbat** [comment]
> Im not sure why not just do it the old fashion way in the appsettings ? And this answer is helpful in any way because?
Did you ever ask yourself why the Author has the appsettings set up the way it is? Just becuase it's "CLEAR" to you does not automatically mean it's clear to everyone else.
Please, if you going to be facetious, rather keep quiet.

**Comment by Duelbat** [comment]
My apologies! Yes, upon re-reading your comment, I realized that I got on my hi-horse earlier. Agreed, it does seem a bit convoluted compared to the vanilla appsettings file.

**Comment by Duelbat** [comment]
Well it looks like the creator of this framework is going to be one of those that I see so often. Just non-responsive. 
If this is how it starts, better just to dump it.
