### ISSUE TITLE
What's the future of Spark?

### ISSUE THREAD

**Issue by skyfallwastaken** [spark-dotnet/framework#74]
Firstly, I want to make it clear that I mean to put no pressure or anything at all, OSS is OSS and anyone can contribute.

However, Spark doesn't seem to have much activity now. Is it because Spark is basically finished, or is it because the idea's unviable, or is it just that you lost interest/don't have the time?

Thanks :)

**Comment by westonwalker** [comment]
The former. It has everything you need to make a SAAS at this point. I'll still accept pull requests, fix bugs, and do upgrades for major .NET releases.
